universe = vanilla
executable = combine.sh
log = $(result).log
error = $(result).err
output= $(result).out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = (Target.HasCHTCStaging == true)
arguments = $(run) $(file0) $(file1) $(file2) $(file3) $(result)
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/combine.py
request_cpus =1
request_memory = 130GB
request_disk = 180GB
queue
