universe = vanilla
executable = convert.sh
log = convert.log
error = convert.err
output= convert.out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = (Target.HasCHTCStaging == true)
arguments = fields_z=0.0.hdf5
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/convert.py
request_cpus = 1
request_memory = 65GB
request_disk = 130GB
queue