universe = vanilla
executable = detection.sh
log = detection.log
error = detection.err
output= detection.out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = (Target.HasCHTCStaging == true)
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/detection.py
request_cpus =1
request_memory = 100GB
request_disk = 105GB
queue
