universe = vanilla
executable = pk.sh
log = pk.log
output = pk.out
error = pk.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = (Target.HasCHTCStaging == true)
arguments = mass_final.hdf5 mass ptlpk.txt
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/pk.py
request_cpus = 1
request_memory = 140GB
request_disk = 40GB
queue