universe = vanilla
log = ptl$(chunk).log
error = ptl$(chunk).error
output= ptl$(chunk).out
executable = ptl.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
arguments = $(chunk) $(ss)
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/ptl.py
Requirements = (Target.HasCHTCStaging == true)
request_cpus = 1
request_memory = 36GB
request_disk = 40GB
queue