universe = vanilla
executable = total_subhalo.sh
log = total_subhalo.log
error = total_subhalo.err
output= total_subhalo.out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = (Target.HasCHTCStaging == true)
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/subhalo/total_subhalo.py
request_cpus =1
request_memory = 120GB
request_disk = 140GB
queue
