universe = vanilla
executable = compare.sh
log = compare.log
error = $(HIfile).err
output= $(HIfile).out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = (Target.HasCHTCStaging == true)
arguments = $(HIfile)
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python27.tar.gz, packages.tar.gz, HIColor/comparison/compare.py
request_cpus = 1
request_memory = 100GB
request_disk = 130GB
queue HIfile from HIfile_list.txt